resolver: lts-12.22

packages:
- jaeger-client
- wai-opentracing
- location:
    git: https://github.com/symbiont-io/thrift.git
    commit: 3c21b48f4e89f7a4ef340741b70013bff2bf6679
    subdirs:
      - lib/hs
  extra-dep: true

extra-deps:
  - serialise-0.2.0.0
  - cryptonite-0.24
